<?php

use Sydor\ProductTabsWidget\Block\Widget\ProductTabsWidget;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Catalog\Helper\Product\Compare;
use Magento\Framework\App\Action\Action;
use Magento\Framework\Escaper;
use Magento\Wishlist\Helper\Data;

/** @var ProductTabsWidget $block */
/** @var Escaper $escaper */
/** @var ProductsList $productList */

?>
<?php if ($activeTabs = $block->getActiveTabs()):
$tabs = []; ?>
<div class="product-tabs-widget">
    <div class="widget-tabs-container">
    <?php foreach ($activeTabs as $tabIndex => $activeTabData):
        $type = 'widget-product-grid';
        $mode = 'grid';
        $image = 'new_products_content_widget_grid';
        $items = $block->getActiveTabCollection($activeTabData)->getItems();
        $productList = $block->productList;
        $showWishlist = true;
        $showCompare = true;
        $showCart = true;
        $description = false;
        $templateType = ReviewRendererInterface::SHORT_VIEW; ?>
        <div id="tab-<?= $activeTabData->getId() ?>" class="block widget widget-tab block-products-list <?= /* @noEscape */
        $mode ?><?= $tabIndex === 1 ? ' active' : '' ?>">
            <?php if ($activeTabData->getTitle()):
                $tabs[$activeTabData->getId()] = $activeTabData->getTitle(); ?>
                <h2 class="block-title"><?= $escaper->escapeHtml(__($activeTabData->getTitle())) ?></h2>
            <?php endif ?>
            <div class="block-content">
                <?= /* @noEscape */
                '<!-- ' . $image . '-->' ?>
                <div class="products-<?= /* @noEscape */
                $mode ?> <?= /* @noEscape */
                $mode ?>">
                    <ol class="product-items <?= /* @noEscape */
                    $type ?><?= $block->isSliderMode() ? ' slider-container' : '' ?>">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <?php if ($iterator++ == 1): ?>
                            <li class="product-item<?= $block->isSliderMode() ? ' slide' : '' ?>">
                            <?php else: ?>
                            </li><li class="product-item<?= $block->isSliderMode() ? ' slide' : '' ?>">
                            <?php endif; ?>
                            <div class="product-item-info">
                                <a href="<?= $escaper->escapeUrl($productList->getProductUrl($_item)) ?>" class="product-item-photo">
                                    <?= $productList->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?= $escaper->escapeHtml($_item->getName()) ?>"
                                           href="<?= $escaper->escapeUrl($productList->getProductUrl($_item)) ?>"
                                           class="product-item-link">
                                            <?= $escaper->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <?php if ($templateType): ?>
                                        <?= $productList->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?= $productList->getProductPriceHtml($_item, $type) ?>

                                    <?= $productList->getProductDetailsHtml($_item) ?>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product-item-inner">
                                            <div class="product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php $postParams = $productList->getAddToCartPostParams($_item); ?>
                                                            <form data-role="tocart-form" data-product-sku="<?= $escaper->escapeHtml($_item->getSku()) ?>" action="<?= $escaper->escapeUrl($postParams['action']) ?>" method="post">
                                                                <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                                <input type="hidden" name="<?= /* @noEscape */
                                                                Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */
                                                                $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                <?= $productList->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        title="<?= $escaper->escapeHtml(__('Add to Cart')) ?>"
                                                                        class="action tocart primary">
                                                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php if ($productList->getBlockHtml('formkey')): ?>
                                                            <script type="text/x-magento-init">
                                                                {
                                                                    "[data-role=tocart-form], .form.map.checkout": {
                                                                        "catalogAddToCart": {
                                                                            "product_sku": "<?= $escaper->escapeJs($_item->getSku()); ?>"
                                                                    }
                                                                }
                                                            }
                                                            </script>
                                                        <?php endif; ?>
                                                        <?php else: ?>
                                                        <?php if ($_item->isAvailable()): ?>
                                                            <div class="stock available">
                                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                                            </div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                                <?php if ($showWishlist || $showCompare): ?>
                                                    <div class="actions-secondary" data-role="add-to-links">
                                                        <?php if ($this->helper(Data::class)->isAllow() && $showWishlist): ?>
                                                            <a href="#"
                                                               data-post='<?= /* @noEscape */
                                                               $productList->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $productList->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                                <span><?= $escaper->escapeHtml(__('Add to Wish List')) ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($productList->getAddToCompareUrl() && $showCompare): ?>
                                                            <?php $compareHelper = $this->helper(Compare::class); ?>
                                                            <a href="#" class="action tocompare" data-post='<?= /* @noEscape */
                                                            $compareHelper->getPostDataParams($_item) ?>' title="<?= $productList->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                                <span><?= $escaper->escapeHtml(__('Add to Compare')) ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                </div>
                <?= $block->getPagerHtml() ?>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
    <?php if ($block->isSliderMode()): ?>
        <script>
            require(['Sydor_ProductTabsWidget/js/products-grid-slider'], function (slider) {
                slider.init('.slider-container');
            });
        </script>
    <?php endif; ?>
    <?php if (count($tabs) > 1): ?>
    <ul class="widget-switcher">
        <?php foreach ($tabs as $id => $label):
        echo '<li target-id="tab-'. $id .'">' . $label . '</li>';
        endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
<?php endif; ?>
